"""add meeting_chunks for RAG

Revision ID: adb157b2c243
Revises: ef701521675a
Create Date: 2026-06-20 11:00:46.256684

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = 'adb157b2c243'
down_revision = 'ef701521675a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_chunks')
    # ### end Alembic commands ###
